name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  NODE_VERSION: 20.17.0

jobs:
  install_test_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Cache node_modules & .next
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .next
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE_VERSION }}-

      - name: Install Dependencies
        run: |
          npm ci --legacy-peer-deps
          npm install --save-dev typescript @types/react @types/node --legacy-peer-deps

      - name: Lint (Optional)
        run: npm run lint || true

      - name: Test (Optional)
        run: npm run test || true

      - name: Prisma Generate
        run: npx prisma generate

      - name: Build
        run: npm run build
