name: Deploy Production

on:
  push:
    branches: [master]

env:
  NODE_VERSION: 20.17.0

jobs:
  deploy_production:
    runs-on: ubuntu-latest

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Vercel Pull (Production)
        run: vercel pull --yes --environment=production --token $VERCEL_TOKEN

      - name: Vercel Build
        run: vercel build --prod --token $VERCEL_TOKEN

      - name: Vercel Deploy
        run: vercel deploy --prebuilt --prod --token $VERCEL_TOKEN --alias ${{ secrets.PRODUCTION_URL }}
